### ISSUE TITLE
Is "Page Public Content Access" required?

### ISSUE THREAD

**Issue by johnty** [dannyvankooten/recent-facebook-posts#36]
[forum on wordpress](https://wordpress.org/support/plugin/recent-facebook-posts/) seem to be abandoned, so trying here...

it looks like the current version live on wordpress.org is not working, as it asks for the ""Page Public Content Access" which is only available for verified "Business Account" holders.

can the author @dannyvankooten confirm this is the case, and that once an app has been created with this permission, that the plugin will work?

Thanks!

**Comment by dannyvankooten** [comment]
hi @johnty,

Sorry, I wouldn't know and have no means to test as I've stopped using Facebook and do not wish to register an account with them ever again. Therefore I've also stopped maintaining this plugin.
